### ISSUE TITLE
Allow for use of multi_json or oj for performance boost

### ISSUE THREAD

**Issue by pineapplethief** [lostisland/faraday_middleware#127]
The title pretty much sums it up, as far as I understand oj is much faster than stdlib json implementation. Some option to be able to swap json parse would be nice I think.

**Comment by iMacTia** [comment]
@pineapplethief we're using the standard JSON library mainly for maintenance reasons and to avoid extra dependencies.
You're absolutely right though on the fact that those libraries are faster, however this usually comes with a compatibility trade-off (e.g. I know `oj` doesn't work with JRuby because is written in C).

As Mislav pointed out, you can very easily write your own parser with a few line of code: https://github.com/lostisland/faraday_middleware/issues/62
