### ISSUE TITLE
Extract information from intermediate redirection

### ISSUE THREAD

**Issue by kiriakosv** [lostisland/faraday_middleware#182]
If I understand correctly, `FaradayMiddleware::FollowRedirects` will keep redirecting (up to a limit) until the response code is not in `FaradayMiddleware::FollowRedirects::REDIRECT_CODES`.

Is there a way to obtain some information that exist in the headers of an intermediate redirection response, or I should write my own middleware?

**Comment by iMacTia** [comment]
Hi @kiriakosv,
You can setup a `callback` that will be called for every redirection. See https://github.com/lostisland/faraday_middleware/blob/master/lib/faraday_middleware/response/follow_redirects.rb#L55

Let me know if this helps so that we can close this issue or feel free to ask any further question.

**Comment by kiriakosv** [comment]
Hi @iMacTia,
Turns out that I didn't need to use callbacks for my use case. Thanks for your help anyway 🙂
