### ISSUE TITLE
undefined method `dependency' for ActiveCampaign::Faraday::Middleware::Request:Class (NoMethodError)

### ISSUE THREAD

**Issue by IvanMuts** [lostisland/faraday_middleware#280]
when i tried to update my rails to rails 7 and ruby 2.7.2, thats the error is was getting. please help.

**Comment by olleolleolle** [comment]
Hi! The API for Faraday 2 has changed slightly, so that the "optional late-loaded dependency method called dependency" is removed. 

You can ask for a lower-than-2 version of Faraday in your Gemfile, to avoid using the new API for your app.

The middleware used has not been updated to support the new API.

**Comment by iMacTia** [comment]
Hi @IvanMuts, this is an issue with the `active_campaign` gem from what I can see.
The reason is because they use the `dependency` method (see https://github.com/mhenrixon/active_campaign/blob/f2298d4da458259e96134fcb0cc25846802a8b91/active_campaign.gemspec#L33), which has been removed in Faraday v2.

However, they declare they're compatible with Faraday v2 in their gemspec (see https://github.com/mhenrixon/active_campaign/blob/master/active_campaign.gemspec#L33).

You should open an issue on their repository and point them to our [UPGRADING.md](https://github.com/lostisland/faraday/blob/main/UPGRADING.md) guide so they can correctly support Faraday v2

**Comment by IvanMuts** [comment]
thanks guys
