### ISSUE TITLE
Update gem to use Gzip Middleware

### ISSUE THREAD

**Issue by keysen** [lostisland/faraday_middleware#93]
Hello,

Can you please update your gem on rubygems to use the latest features?

Ty.

**Comment by zzk** [comment]
:+1:

**Comment by laysakura** [comment]
:+1:

**Comment by mislav** [comment]
@sferik Would you be available to cut a release of this soon?

@keysen Just checking if you're aware that you probably don't need the Gzip middleware if you're using the default net_http adapter (since net/http in Ruby 1.9+ handles that under the hood)?

**Comment by zzk** [comment]
@sferik you just released 0.9.1 but I can not see gzip in this release. May I ask you why?

**Comment by johnromani90** [comment]
@mislav is it known that default adapter does not handle POST responses automatically with Gzip?

**Comment by iMacTia** [comment]
@johnromani90 This Issue is extremely old and the GZIP middleware has been already released.
You can find the file here: https://github.com/lostisland/faraday_middleware/blob/master/lib/faraday_middleware/gzip.rb

I'm closing this issue but if you have any issue using the middleware then feel free to open a new one
